#!/bin/bash
emacs=${EMACS:=emacs}
# emacsflags=${EMACSFLAGS:=}
cask=${CASK:=cask}
emacsbatch="${EMACS} -Q --batch ${EMACSFLAGS}"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PWD=$(pwd)

print_help () {
echo <<EOF
usage: indent-stan-files input_file [output_file]
EOF
}

# From http://stackoverflow.com/questions/3915040/bash-fish-command-to-print-absolute-path-to-a-file
get_abs_filename() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

# See http://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
command-exists () {
    hash $1 2>/dev/null 
}

indent-stan () {
    cd ${DIR}
    ${cask} \
	exec ${emacs} \
        -Q --batch \
	--eval="(setq vc-handled-backends ())" \
	--eval="(require 'stan-mode)" \
	-f flymake-mode-off \
	"$1" \
	-f stan-mode \
	--eval="(indent-region (point-min) (point-max))" \
	--eval="(write-file \"$2\")" 
}

# Check that there is at least one file
if [ $# -eq 0 ]
then
   echo "error: indent-stan-files requires at least one argument." 1>&2
   print_help
   exit 1
fi

# Check for existence of file
ls $1 2> /dev/null | grep $1 > /dev/null
if [ $? != 0 ]
then
    echo "error: indent-stan-files: $1 not found." 1>&2
    print_help
    exit 1
fi

command-exists ${emacs} || { echo echo >&2 "${emacs} not found. Put the path to the directory in which emacs is installed in the PATH or set the environment variable EMACS to the path to the emacs binary. Aborting."; exit 1; }
command-exists ${cask} || { echo >&2 "${cask} not found. Put the path to the directory in which cask is installed in the PATH. See http://cask.readthedocs.org/en/latest/guide/installation.html to install cask. Aborting."; exit 1; }


# echo "Indenting $1 with emacs in batch mode"
inputfile=$(get_abs_filename "$1")
outputfile=$(get_abs_filename "${2:-$inputfile}")
indent-stan "${inputfile}" "${outputfile}"
exit 0

