(source gnu)
(source melpa)

(package-file "stan-mode.el")
(depends-on "yasnippet")

(development
 (depends-on "shut-up") ;; quiet emacs
 (depends-on "buttercup")
 (depends-on "package-lint")
 (depends-on "elisp-lint"))
