import json
import re
import sys
import os.path

_TEMPLATE = """;;; {el_file} -- variables used by `stan-mode'

;;; Commentary:

;; DO NOT EDIT! file auto generated by {py_file}

;;; Code:

(defconst stan-language-version "{version}"
  "Stan modeling language version supported by `stan-mode'.")

(defconst stan-types-list
  {types}
  "List of data types in Stan.

   This includes both variable declariations and function return types.")

(defconst stan-function-return-types-list
  {return_types}
  "List of return types of Stan functions.")

(defconst stan-blocks-list
  {blocks}
  "List of the names of blocks in Stan.")

(defconst stan-range-constraints-list
  {range_constraints}
  "List of range constraint keywords in Stan.")

(defconst stan-keywords-list
  {keywords}
  "List of keywords in Stan.")

(defconst stan-functions-list
  {functions}
  "List of functions in Stan.")

(defconst stan-distribution-list
  {distributions}
  "List of distributions in Stan.")

(defconst stan-reserved-list
  {reserved}
  "List of reserved keywords in Stan.")

(defconst stan-deprecated-function-list
  {deprecated}
  "List of deprecated functions in Stan.")

(provide 'stan-keywords-lists)

;;; {el_file} ends here

"""

DISTR_PARTS = ('Continuous Distributions', 'Discrete Distributions')

def sexp(x):
    return "'(\n" + '\n'.join('    "%s"' % atom for atom in x) + "\n    )"

def read_json(filename):
    with open(filename, "r") as f:
        data = json.load(f)

    keywords = set()
    for k in ('control', 'other', 'functions'):
        for x in data['keywords'][k]:
            keywords.add(x)
    keywords = sorted(list(keywords))
    reserved = set()
    for k in data['reserved']:
        for x in data['reserved'][k]:
            if x not in keywords:
                 reserved.add(x)
    reserved = sorted(list(reserved))
    types = sorted(data['types']['variable'])
    return_types = sorted(data['types']['return'])
    blocks = sorted(data['blocks'])
    range_constraints = sorted(data['keywords']['range_constraints'])
    functions = sorted(k for k, v in data['functions'].items()
                       if not (v['operator'] or v['keyword'] or v['deprecated']))
    deprecated = sorted(k for k, v in data['functions'].items() if v['deprecated'])
    distributions = sorted([v['sampling'] for k, v in data['functions'].items() if v['sampling']])
    
    
    return {
        'blocks' : sexp(sorted(blocks)),
        'range_constraints' : sexp(sorted(range_constraints)),
        'distributions' : sexp(sorted(distributions)),
        'functions' : sexp(sorted(functions)),
        'keywords' : sexp(sorted(keywords)),
        'reserved' : sexp(sorted(reserved)),
        'types' : sexp(sorted(types)),
        'return_types' : sexp(sorted(return_types)),
        'version' : data['version'],
        'deprecated' : sexp(sorted(deprecated)),
        'py_file' : os.path.split(__file__)[1]
    }

def create_code(data, dst):
    data.update({'el_file' : os.path.split(dst)[1]})
    with open(dst, 'w') as f:
        f.write(_TEMPLATE.format(**data))

if __name__ == '__main__':
    create_code(read_json(sys.argv[1]), sys.argv[2])

